// src/frontend/vue/components/Chat.vue
<script setup lang="ts">
import { ref } from "vue";
import { useAIStream } from "@absolutejs/absolute/vue/ai";

const PROVIDERS = ["anthropic", "openai", "ollama"];
const provider = ref("anthropic");
const inputValue = ref("");

const { messages, send, cancel, isStreaming, error } = useAIStream("/chat");

const handleSubmit = (evt: Event) => {
  evt.preventDefault();
  const value = inputValue.value.trim();
  if (!value) return;
  send(`${provider.value}:${value}`);
  inputValue.value = "";
};
</script>

<template>
  <div class="chat-container">
    <div class="provider-selector">
      <button
        v-for="prov in PROVIDERS"
        :key="prov"
        :class="{ active: prov === provider }"
        type="button"
        @click="provider = prov"
      >
        {{ prov }}
      </button>
    </div>

    <div class="messages">
      <div v-if="messages.length === 0" class="empty-state">
        Send a message to start chatting. Try "What's the weather in Tokyo?"
      </div>
      <div
        v-for="msg in messages"
        :key="msg.id"
        class="message"
        :data-role="msg.role"
      >
        {{ msg.content }}
        <span v-if="msg.isStreaming" class="cursor" />
        <template v-if="msg.toolCalls">
          <div
            v-for="tool in msg.toolCalls"
            :key="`${msg.id}-${tool.name}`"
            class="tool-status"
            :class="{ running: !tool.result }"
          >
            {{ tool.result ? `${tool.name}: ${tool.result}` : `Running ${tool.name}...` }}
          </div>
        </template>
      </div>
    </div>

    <div v-if="error" class="tool-status running">Error: {{ error }}</div>

    <form class="chat-form" @submit="handleSubmit">
      <input
        v-model="inputValue"
        autocomplete="off"
        :disabled="isStreaming"
        name="input"
        :placeholder="`Ask ${provider} anything...`"
      />
      <button v-if="isStreaming" class="cancel" type="button" @click="cancel">
        Stop
      </button>
      <button v-else type="submit">Send</button>
    </form>
  </div>
</template>

// src/frontend/react/components/Chat.tsx
import { useState, useRef, useEffect } from "react";
import { useAIStream } from "@absolutejs/absolute/react/ai";

const PROVIDERS = ["anthropic", "openai", "ollama"];

export const Chat = () => {
  const [provider, setProvider] = useState("anthropic");
  const { messages, send, cancel, isStreaming, error } = useAIStream("/chat");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSubmit = (evt: React.FormEvent<HTMLFormElement>) => {
    evt.preventDefault();
    const form = evt.currentTarget;
    const input = form.elements.namedItem("input") as HTMLInputElement;
    const value = input.value.trim();

    if (!value) {
      return;
    }

    send(`${provider}:${value}`);
    input.value = "";
  };

  return (
    <div className="chat-container">
      <div className="provider-selector">
        {PROVIDERS.map((prov) => (
          <button
            key={prov}
            className={prov === provider ? "active" : ""}
            onClick={() => setProvider(prov)}
            type="button"
          >
            {prov}
          </button>
        ))}
      </div>

      <div className="messages">
        {messages.length === 0 && (
          <div className="empty-state">
            Send a message to start chatting. Try &quot;What&apos;s the weather in Tokyo?&quot;
          </div>
        )}
        {messages.map((msg) => (
          <div key={msg.id} className="message" data-role={msg.role}>
            {msg.content}
            {msg.isStreaming && <span className="cursor" />}
            {msg.toolCalls?.map((tool) => (
              <div
                key={`${msg.id}-${tool.name}`}
                className={`tool-status ${tool.result ? "" : "running"}`}
              >
                {tool.result
                  ? `${tool.name}: ${tool.result}`
                  : `Running ${tool.name}...`}
              </div>
            ))}
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {error && <div className="tool-status running">Error: {error}</div>}

      <form className="chat-form" onSubmit={handleSubmit}>
        <input
          ref={inputRef}
          autoComplete="off"
          disabled={isStreaming}
          name="input"
          placeholder={`Ask ${provider} anything...`}
        />
        {isStreaming ? (
          <button className="cancel" onClick={cancel} type="button">
            Stop
          </button>
        ) : (
          <button type="submit">Send</button>
        )}
      </form>
    </div>
  );
};
